# Sidekiq config example
#---
:verbose: true
:concurrency:  8
:queues:
  - default
  - stats

schedule:
  recheck_sources:
    class: "Extract::RecheckSourcesWorker"
    every: "5m"
    queue: "default"
    description: "Fetch updates from sources"

  recrawl:
    class: "Extract::RecrawlerWorker"
    every: "10m"
    queue: "default"
    description: "Recrawl failed urls"

  update_scores:
    class: "Score::CheckWorker"
    every: "10m"
    queue: "default"
    description: "Update facebook's likes and another metricks for each item"
